"""
Content-Aware Ad Banner Layout Generation with Two-Stage Chain-of-Thought
Based on the paper: Content-Aware Ad Banner Layout Generation with Two-Stage Chain-of-Thought in Vision Language Models

This module implements:
1. Placement Plan Generation using VLM
2. HTML Layout Generation based on the plan
3. Two-stage Chain-of-Thought prompting for better control
"""

from __future__ import annotations

from typing import Dict, Any, Optional, List, Tuple
from dataclasses import dataclass
from pathlib import Path
import json
import os

try:
    from langchain_openai import ChatOpenAI
    from langchain_core.messages import HumanMessage, SystemMessage
    LANGCHAIN_AVAILABLE = True
except ImportError:
    LANGCHAIN_AVAILABLE = False


@dataclass
class LayoutElement:
    """Represents a layout element (text, logo, underlay)"""
    element_type: str  # "text", "logo", "underlay"
    position: Tuple[int, int]  # (x, y)
    size: Tuple[int, int]  # (width, height)
    content: Optional[str] = None


@dataclass
class PlacementPlan:
    """Text-based placement plan generated by VLM"""
    plan_text: str
    considerations: List[str]
    element_placements: Dict[str, str]


class ContentAwareLayoutGenerator:
    """
    Generates content-aware ad banner layouts using Vision-Language Models
    with two-stage Chain-of-Thought prompting.
    """

    def __init__(self, config: Any, vlm_model: str = "gpt-4o"):
        """
        Initialize Content-Aware Layout Generator
        
        Args:
            config: AppConfig object
            vlm_model: VLM model name (default: gpt-4o)
        """
        self.config = config
        self.vlm_model = vlm_model
        
        if not LANGCHAIN_AVAILABLE:
            raise ImportError("LangChain is required for ContentAwareLayoutGenerator")
        
        openai_api_key = os.getenv("OPENAI_API_KEY") or getattr(config, "openai_api_key", None)
        if not openai_api_key:
            raise ValueError("OPENAI_API_KEY is required")
        
        self.llm = ChatOpenAI(
            model_name=vlm_model,
            temperature=0.7,
            api_key=openai_api_key
        )
        
        # Few-shot examples for placement plan generation
        self.placement_plan_examples = self._load_placement_examples()
        
        # Few-shot examples for HTML layout generation
        self.html_layout_examples = self._load_html_examples()

    def _load_placement_examples(self) -> List[Dict[str, str]]:
        """Load few-shot examples for placement plan generation"""
        return [
            {
                "instruction": "Please tell me the requirements where to place the ad elements.",
                "constraint": "Please be aware of the contents of this image.",
                "element_types": "text 0 | text 1 | underlay 2",
                "output": "Placement Plan:\n- Text 0: Bottom center to ensure it does not overlap above the waist of man and woman.\n- Text 1: Under Text 0, aligned with Text 0.\n- Underlay 2: Behind Text 0 and Text 1 to avoid overlapping humans as possible."
            }
        ]

    def _load_html_examples(self) -> List[Dict[str, str]]:
        """Load few-shot examples for HTML layout generation"""
        return [
            {
                "placement_plan": "Text 0: Bottom center\nText 1: Under Text 0\nUnderlay 2: Behind Text 0 and Text 1",
                "canvas_size": "102px x 150px",
                "output": """<html>
<body>
<div class="canvas" style="left:0px; top:0px; width:102px; height:150px"></div>
<div class="text" style="left:2px; top:113px; width:95px; height:10px"></div>
<div class="text" style="left:2px; top:124px; width:95px; height:9px"></div>
<div class="underlay" style="left:0px; top:111px; width:102px; height:24px"></div>
</body>
</html>"""
            }
        ]

    def generate_placement_plan(
        self,
        background_image_path: str,
        element_types: List[str],
        canvas_size: Tuple[int, int] = (1024, 1500)
    ) -> PlacementPlan:
        """
        Stage 1: Generate text-based placement plan using VLM
        
        Args:
            background_image_path: Path to background image
            element_types: List of element types to place (e.g., ["text", "logo", "underlay"])
            canvas_size: Canvas dimensions (width, height)
        
        Returns:
            PlacementPlan object
        """
        # Read image (base64 encode for VLM)
        import base64
        with open(background_image_path, "rb") as f:
            image_data = base64.b64encode(f.read()).decode('utf-8')
        
        # Construct prompt with few-shot examples
        element_constraint = " | ".join([f"{et} {i}" for i, et in enumerate(element_types)])
        
        prompt = f"""Instruction: Please tell me the requirements where to place the ad elements.
Constraint: Please be aware of the contents of this image.
Element Type Constraint: {element_constraint}

Example Output:
{self.placement_plan_examples[0]['output']}

Now analyze this image and generate a placement plan:"""
        
        messages = [
            SystemMessage(content="You are an expert in ad layout design. Analyze images and create placement plans that avoid important visual elements."),
            HumanMessage(content=[
                {"type": "text", "text": prompt},
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_data}"}}
            ])
        ]
        
        response = self.llm.invoke(messages)
        plan_text = response.content
        
        # Parse placement plan
        considerations = []
        element_placements = {}
        
        for line in plan_text.split('\n'):
            if ':' in line and '-' in line:
                parts = line.split(':', 1)
                if len(parts) == 2:
                    element_id = parts[0].strip().replace('-', '').strip()
                    placement_desc = parts[1].strip()
                    element_placements[element_id] = placement_desc
            elif line.strip() and not line.startswith('Placement Plan'):
                considerations.append(line.strip())
        
        return PlacementPlan(
            plan_text=plan_text,
            considerations=considerations,
            element_placements=element_placements
        )

    def generate_html_layout(
        self,
        background_image_path: str,
        placement_plan: PlacementPlan,
        element_types: List[str],
        canvas_size: Tuple[int, int] = (1024, 1500)
    ) -> str:
        """
        Stage 2: Generate HTML layout based on placement plan
        
        Args:
            background_image_path: Path to background image
            placement_plan: PlacementPlan from stage 1
            element_types: List of element types
            canvas_size: Canvas dimensions
        
        Returns:
            HTML layout code
        """
        import base64
        with open(background_image_path, "rb") as f:
            image_data = base64.b64encode(f.read()).decode('utf-8')
        
        element_constraint = " | ".join([f"{et} {i}" for i, et in enumerate(element_types)])
        
        prompt = f"""Instruction: Please generate a layout based on the given information. You need to ensure that the generated layout looks realistic, with elements well aligned and avoiding unnecessary overlap.
Task Description: content-aware layout generation
Please place the following elements to avoid salient content, and underlay must be the background of text or logo.
Canvas Size: canvas width is {canvas_size[0]}px, canvas height is {canvas_size[1]}px

Element Type Constraint: {element_constraint}
Placement Plan:
{placement_plan.plan_text}

Generate the HTML layout code:"""
        
        messages = [
            SystemMessage(content="You are an expert in HTML layout generation for advertisements. Generate precise HTML code with pixel-perfect positioning."),
            HumanMessage(content=[
                {"type": "text", "text": prompt},
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_data}"}}
            ])
        ]
        
        response = self.llm.invoke(messages)
        html_code = response.content
        
        # Extract HTML from response (might be wrapped in markdown code blocks)
        if "```html" in html_code:
            html_code = html_code.split("```html")[1].split("```")[0].strip()
        elif "```" in html_code:
            html_code = html_code.split("```")[1].split("```")[0].strip()
        
        return html_code

    def generate_layout(
        self,
        background_image_path: str,
        element_types: List[str],
        canvas_size: Tuple[int, int] = (1024, 1500)
    ) -> Dict[str, Any]:
        """
        Complete two-stage layout generation pipeline
        
        Args:
            background_image_path: Path to background image
            element_types: List of element types to place
            canvas_size: Canvas dimensions
        
        Returns:
            Dictionary with placement_plan and html_layout
        """
        # Stage 1: Generate placement plan
        placement_plan = self.generate_placement_plan(
            background_image_path=background_image_path,
            element_types=element_types,
            canvas_size=canvas_size
        )
        
        # Stage 2: Generate HTML layout
        html_layout = self.generate_html_layout(
            background_image_path=background_image_path,
            placement_plan=placement_plan,
            element_types=element_types,
            canvas_size=canvas_size
        )
        
        return {
            "placement_plan": placement_plan,
            "html_layout": html_layout,
            "canvas_size": canvas_size
        }

